server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/crochet_db
    username: crochet_admin
    password: SecretPassword123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
