server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/crochet_db?currentSchema=user_service
    username: crochet_admin
    password: SecretPassword123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    create-schemas: true
    default-schema: user_service
    schemas: user_service
