server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crochet_db?currentSchema=ai_service
    username: crochet_admin
    password: SecretPassword123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    create-schemas: true
    default-schema: ai_service
    schemas: ai_service

gemini:
  api:
    key: ${GEMINI_API_KEY:mock-local-key}
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}
