spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true

internal:
  jwt:
    secret: ${INTERNAL_JWT_SECRET}

llm:
  text-generation-provider: ${LLM_TEXT_GENERATION_PROVIDER:gemini} #gemini or openai
  image-generation-provider: ${LLM_IMAGE_GENERATION_PROVIDER:pollinations} #pollinations or gemini or openai
  image-generation-token-cost: ${IMAGE_GENERATION_TOKEN_COST:2500} #image generation token cost for pollinations.ai
  image-generation-default-width: ${IMAGE_GENERATION_DEFAULT_WIDTH:512} #image generation default width
  image-generation-default-height: ${IMAGE_GENERATION_DEFAULT_HEIGHT:512} #image generation default height
  image-generation-default-model: ${IMAGE_GENERATION_DEFAULT_MODEL:flux} #image generation default model

db:
  encryption-secret: ${DB_ENCRYPTION_SECRET}

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  include-application-name: true
  structured:
    format:
      console: logstash # Automatically bundles active traceId and spanId fields into every log line
management:
  tracing:
    sampling:
      probability: 1.0 # Trace 100% of requests for development and monitoring purposes
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
